
import Footer from '@/component/Footer';
import Header from '@/component/Header/Header';
import Providers from '@/component/Providers';
import '../styles/globals.css';
import '../styles/header.scss';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default  function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Providers>
          
       <Header/>

        {children}

        <Footer/>
      </Providers>
        </body>
    </html>
  )
}
